### ISSUE TITLE
usb c legal requirement in europe

### ISSUE THREAD

**Issue by RustoMCSpit** [zynthian/zynthian-hw#10]
this project will need to support usb c to be legal within the eu in a few months, just a heads up

**Comment by jofemodo** [comment]
We just dropped USB-C because it's not reliable enough for stage and reharsall.  Anyway, zynthian is not affected by the "law":

"The legislation covers mobile phones, tablets, digital cameras, headphones, headsets, handheld videogame consoles, portable speakers, e-readers, keyboards, mice, earbuds and portable navigation devices. Laptops will have to be adapted to the requirements 40 months after the law enters into force."

Zynthian is a "musical instrument", so no need to worry about.

Thanks!

**Comment by RustoMCSpit** [comment]
> We just dropped USB-C because it's not reliable enough for stage and reharsall. 

what do you mean
